spring:
  profiles:
    active: ${APP_ENV:dev}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
