spring:
  profiles:
    active: ${APP_ENV}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always