spring:
  datasource:
    name: postgres
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update